version: '2'

services:

  mongo:
    image: minhacidadetransparente/mongo

  api:
    image: minhacidadetransparente/api
    ports:
      - "8001:80"
    depends_on:
      - mongo
    volumes:
      - /Users/jeanbauer/Desktop/projects/sentinela/Api:/usr/src/app
    environment:
      - NODE_ENV=dev
    command: npm install
    command: npm start
